/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../src/components/composition/BaseButton.vue')['default']
    BaseCard: typeof import('./../src/components/composition/BaseCard.vue')['default']
    BaseDialog: typeof import('./../src/components/composition/BaseDialog.vue')['default']
    BaseDropdown: typeof import('./../src/components/composition/BaseDropdown.vue')['default']
    BaseInput: typeof import('./../src/components/composition/BaseInput.vue')['default']
    BaseSkeleton: typeof import('./../src/components/composition/BaseSkeleton.vue')['default']
    BaseSwitch: typeof import('./../src/components/composition/BaseSwitch.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    LangDropdown: typeof import('./../src/components/custom/LangDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/composition/SvgIcon.vue')['default']
    ThemeSwitch: typeof import('./../src/components/custom/ThemeSwitch.vue')['default']
    TinymceEditor: typeof import('./../src/components/composition/Tinymce/TinymceEditor.vue')['default']
  }
}
